VideoStream:
  _target_: samcam.stream_buffer.StreamBuffer
  video_source: 1
  buffer_size: 1
  frame_width: 640
  frame_height: 480

sam2_checkpoint: ./lib/sam2/checkpoints/sam2.1_hiera_tiny.pt
model_cfg: configs/sam2.1/sam2.1_hiera_t.yaml # relative path
device: cuda
frame_buffer: ./outputs/frame_buffer
